x-service-default: &service
  image: rest-api-go
  init: true
  build:
    context: ./
    dockerfile: ./Dockerfile
  env_file:
    - ./.env
  networks:
    - rest-api-go_network
  volumes:
    - ./:/rest-api-go/:delegated

services:
  rest-api-go:
    <<: *service
    working_dir: /rest-api-go
    tty: true
    command: go tool air -c .air.toml
    expose:
      - '8089'
    ports:
      - '8089:8089'

  postgresql:
    container_name: 'rest-api-go-postgres'
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./infrastructure/db:/docker-entrypoint-initdb.d
      - rest-api-go-postgres-data:/var/lib/postgresql/data
      - ./testdata:/testdata
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=rest-api-go-db
      - POSTGRES_PASSWORD=password
    networks:
      - rest-api-go_network
    hostname: docker-postgres
    ports:
      - 5732:5432
      

networks:
  rest-api-go_network:
    external: true

volumes:
  rest-api-go-postgres-data:
    external:
      name: rest-api-go_postgres-data
